
authing:
  user-pool:
    user-pool-id: 62fdba62ce9b88676861a14e
    secret: e81f5c2b71e5c3429b33c30a837194a5

  app:
    app-id: 62fdba62b0c42c5a0c4336b8
    app-host: https://pikfffmdebgc-demo.authing.cn

  exclude-paths:
    - /login
    - /hello